---
title: "Imports and Exports of India: Make in India movement (Dashboard-3)"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(plotly)
library(dplyr)
library(readr)

countries = read_csv("C:\\Users\\Debargha Guha Neogi\\Desktop\\Winter Sem 2021-22\\CSE3020-DV\\DV Project\\country_codes.csv")

dataset_df = read_csv("C:\\Users\\Debargha Guha Neogi\\Desktop\\Winter Sem 2021-22\\CSE3020-DV\\DV Project\\exports and imports of india(1997-2022) - exports and imports.csv")
dataset_df <- data.frame(tolower(dataset_df$Country), dataset_df$Export, dataset_df$Import, dataset_df$Total_Trade, dataset_df$Trade_Balance, dataset_df$Year_start, dataset_df$Year_end)

countries <- data.frame(tolower(countries$Country), countries$Code)

dataset_df <- inner_join(dataset_df, countries, by = c("tolower.dataset_df.Country." = "tolower.countries.Country."))

dataset_df$dataset_df.Year_start[dataset_df$dataset_df.Year_start==97]<-1997
dataset_df$dataset_df.Year_start[dataset_df$dataset_df.Year_start==98]<-1998
dataset_df$dataset_df.Year_start[dataset_df$dataset_df.Year_start==99]<-1999
dataset_df <- subset(dataset_df, select = -c(dataset_df.Year_end))
colnames(dataset_df)[which(names(dataset_df)=="tolower.dataset_df.Country.")] <- "Country"
colnames(dataset_df)[which(names(dataset_df)=="dataset_df.Year_start")] <- "Year"
colnames(dataset_df)[which(names(dataset_df)=="dataset_df.Export")] <- "Export"
colnames(dataset_df)[which(names(dataset_df)=="dataset_df.Import")] <- "Import"
colnames(dataset_df)[which(names(dataset_df)=="dataset_df.Total_Trade")] <- "Total_Trade"
colnames(dataset_df)[which(names(dataset_df)=="dataset_df.Trade_Balance")] <- "Trade_Balance"
dataset_df <- na.omit(dataset_df)
export1 <- sum(dataset_df[which(dataset_df$Year < 2014), 2], na.rm = TRUE)
import1 <- sum(dataset_df[which(dataset_df$Year < 2014), 3], na.rm = TRUE)
labels1 <- c("Export", "Import")
df1 <- data.frame(matrix(c("Export",export1, "Import", import1), nrow = 2, ncol = 2, byrow = TRUE))

import2 <- sum(dataset_df[which(dataset_df$Year > 2014), 3], na.rm = TRUE)
export2 <- sum(dataset_df[which(dataset_df$Year > 2014), 2], na.rm = TRUE)
df2 <- data.frame(matrix(c("Export",export2, "Import", import2), nrow = 2, ncol = 2, byrow = TRUE))
df3 <- dataset_df[dataset_df$Year < 2014,]
temp = aggregate(df3$Export, by = list(df3$Country), FUN = sum)
output <- data.frame(temp[order(-temp$x),][1:10,])
df4 <- dataset_df[dataset_df$Year > 2014,]
temp1 = aggregate(df4$Export, by = list(df4$Country), FUN = sum)
output1 <- data.frame(temp1[order(-temp1$x),][1:10,])
```

Column {data-width=500}
-----------------------------------------------------------------------

### Export and Import Analysis

```{r}
fig <- plot_ly()%>%
  config(displayModeBar = FALSE)

fig <- fig %>% add_pie(df1, labels = ~df1$X1, values = ~df1$X2, name = "Before 2014", domain = list(x = c(0, 0.4), y = c(0.4, 1)))


fig <- fig %>% add_pie(df2, labels = ~df2$X1, values = ~df2$X2, name = "After 2014", domain = list(x = c(0.6, 1), y = c(0.4, 1)))

fig
```



Column {data-width=500}
-----------------------------------------------------------------------

### Top 10 Export Partners of India (Before 2014)

```{r}
fig1 <- plot_ly(output, x = ~output$Group.1, y = ~output$x, labels = c("Country", "Million USD"), name = "Top 10 Export Partners of India (Before 2014)")%>%
  config(displayModeBar = FALSE)
fig1 <- fig1 %>% add_trace(type = 'bar',marker = list(color = "blue", line = list(color = "black", width = 1)))
fig1 <- fig1%>%layout(xaxis = list(title = "Country"), yaxis = list(title = "USD (Millions)"))
fig1
```

### Top 10 Export Partners of India (After 2014)

```{r}
fig2 <- plot_ly(output1, x = ~output1$Group.1, y = ~output1$x, labels = c("Country", "Million USD"))%>%
  config(displayModeBar = FALSE)
fig2 <- fig2 %>% add_trace(type = 'bar',marker = list(color = "blue", line = list(color = "black", width = 1)))
fig2 <- fig2%>%layout(xaxis = list(title = "Country"), yaxis = list(title = "USD (Millions)"))
fig2
```

